on:
  push:
    branches:
      - master
jobs:
  deploy_build_dev:
    name: Build and deploy dev container
    env:
      AZURE_CONTAINER_REGISTRY_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with: 
          fetch-depth: '0'

      - name: tag_code
        id: tag
        uses: anothrNick/github-tag-action@1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch


      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t base --build-arg GITHUB_SHA_ARG=${{ github.sha }}  --build-arg TAG_VERSION=${{  steps.tag.outputs.new_tag }} .

      - name: Tag :latest
        run: docker tag base $AZURE_CONTAINER_REGISTRY_SERVER/cv-19-benefit:latest

      - name: Tag :steps.tag.output.new_tag
        run: docker tag base $AZURE_CONTAINER_REGISTRY_SERVER/cv-19-benefit:${{ steps.tag.outputs.new_tag }}

      - name: Push container to Azure Container Registry
        run: docker push $AZURE_CONTAINER_REGISTRY_SERVER/cv-19-benefit

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'EsPbDtsCb19AppService'
          slot-name: 'dev'
          images: '${{ secrets.AZURE_CONTAINER_REGISTRY_SERVER }}/cv-19-benefit:${{ steps.tag.outputs.new_tag }}'

      - name: Azure logout
        run: |
          az logout
